# Generated by Django 5.2 on 2025-04-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userotpdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seeker', 'House Seeker'), ('owner', 'Property Owner'), ('manager', 'Property Manager'), ('admin', 'Administrator')], default='seeker', max_length=20),
        ),
    ]
